#!/bin/sh
set -e

VENV_DIR="/usr/lib/downloadthis/venv"

case "$1" in
    configure)
        python3 -m venv "$VENV_DIR" --system-site-packages
        "$VENV_DIR/bin/pip" install --quiet --upgrade \
            "ttkbootstrap>=1.10" "tkinterdnd2>=0.3" "yt-dlp>=2024.1"
        ;;
esac

#DEBHELPER#
exit 0
